version: '3.8'

services:
  # reqgpt:
  #   image: specmap:3.0
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - /opt/bihua/reqgpt/data:/opt/bihua/reqgpt/data
  #   depends_on:
  #     - neo4j

  neo4j:
    image: neo4j:5.22.0
    # image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/sw2201!@#"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: "[\"apoc\", \"graph-data-science\"]"
    volumes:
      - ./data/neo4j_db/data:/data
      - ./data/neo4j_db/logs:/logs
      - ./data/neo4j_db/import:/var/lib/neo4j/import
      - ./data/neo4j_db/plugins:/plugins

